# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6aadbe18cd125a9d859022f9580951b9a9db80398a00b0ee70f57abb2d3253b0e52e966f43e15535dcb8365be1ac7f319bcdc884299e735d72391509689819b
  twitter_api_key: us2xgxIiKeDIjeGRfDEDzGNn0
  twitter_api_secret: fK5j7bPjHT3D9aURyfJ8V9gi5rLGAKk9JCwyfc39hc3DSBhVJN
  twitter_access_token: 155796367-I5hJlPji66kc7mlJTAsUvLlZ1hDRsfO7gapnpiwR
  twitter_access_token_secret: Jyenyrsn7wqGsspHPAnXogOo17Ml1K9BeiPdXoTVoWAeH
  google_maps_api_key: AIzaSyC5NtzJSQmeqYUK9DBfWVq5YeXtrDYuzzU

test:
  secret_key_base: 35a7eb1a5d247a9528e088038055d9dcd8782b622d7180f184f663ed53fc76f81d55ba4624fcf58d947af050bbd9b5c9fa1f96ae02562be4c84c22a39e6881e8
  twitter_api_key: us2xgxIiKeDIjeGRfDEDzGNn0
  twitter_api_secret: fK5j7bPjHT3D9aURyfJ8V9gi5rLGAKk9JCwyfc39hc3DSBhVJN
  twitter_access_token: 155796367-I5hJlPji66kc7mlJTAsUvLlZ1hDRsfO7gapnpiwR
  twitter_access_token_secret: Jyenyrsn7wqGsspHPAnXogOo17Ml1K9BeiPdXoTVoWAeH
  google_maps_api_key: AIzaSyC5NtzJSQmeqYUK9DBfWVq5YeXtrDYuzzU

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
  twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  twitter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
